services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./src/theme:/var/www/html/wp-content/themes/theme
      - ./src/plugin:/var/www/html/wp-content/plugins/plugin
      - ./www:/var/www/html/

  wpcli:
    # use like so: "docker-compose run --rm wpcli WORDPRESS_COMMAND"
    image: "wordpress:cli"
    user: "33"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DEBUG: 1
    command: >
      /bin/sh -c '
      sleep 30; # TODO: Wait for db service to be ready
      wp core install --path="/var/www/html" --url="http://localhost" --title="Local Wordpress By Docker" --admin_user=admin --admin_password=secret --admin_email=foo@bar.com
      '
    depends_on:
      - wordpress
      - db
    volumes:
      - ./www:/var/www/html/

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql

# volumes:
#   db:
